# Generated by Django 6.0.2 on 2026-03-10 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerycustomer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grocerycustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='supplier_invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerypurchaseitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocerypurchaseitem',
            name='received_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='grocerypurchaseitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerypurchaseitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grocerysale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerysale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grocerysale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerysale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerysaleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerysaleitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.grocerystock'),
        ),
        migrations.AddField(
            model_name='grocerysaleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grocerysaleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grocerystock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerystock',
            name='rack_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocerystock',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocerystockadjustment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grocerystocktransfer',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocerysupplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grocerypurchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('partial', 'Partial Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='grocerysale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('credit', 'Credit')], default='cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='grocerysale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('returned', 'Returned')], default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='grocerystocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='GrocerySaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='grocery.grocerysale')),
            ],
        ),
        migrations.CreateModel(
            name='GrocerySaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grocery.groceryproduct')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery.grocerysalereturn')),
            ],
        ),
    ]
