# Generated by Django 6.0.2 on 2026-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_pharmacyproduct_image_pharmacyproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
        migrations.AddField(
            model_name='pharmacycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
